language: java

jdk:
    - oraclejdk7
    - openjdk7

install:
    - sudo apt-get install graphviz
    - mvn install -q -am -pl genomix/genomix-driver/ -DskipTests=true # only install driver's prereq's

before_script:
    - cd genomix/genomix-pregelix/
    - java -classpath target/genomix-pregelix-0.2.10-SNAPSHOT-jar-with-dependencies.jar:target/test-classes/ edu.uci.ics.genomix.pregelix.JobGen.JobGenerator
    - cd ../..
script:
    - cd genomix
    - mvn package -q -e
    - ls -t */target/surefire-reports/*.txt | xargs tail -n +1  # show test reports in the order they ran
