language: java
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6

script: mvn clean package -q -am -pl genomix/genomix-driver
install: mvn install -q -am -pl genomix/genomix-driver -DskipTests=true
