language: java

jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6

install:
    - sudo apt-get install graphviz
    - mvn install -q -DskipTests=true

before_script:
    - java -classpath genomix/genomix-pregelix/target/genomix-pregelix-0.2.10-SNAPSHOT-jar-with-dependencies.jar:genomix/genomix-pregelix/target/test-classes/ edu.uci.ics.genomix.pregelix.JobGen.JobGenerator

script:
    - mvn package -q -am -pl genomix/genomix-driver
