language: java

jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6

before_install: sudo apt-get install graphviz

install: mvn install -q -am -pl genomix/genomix-driver -DskipTests=true

script: mvn clean package -q -am -pl genomix/genomix-driver
